
apiVersion: v1
kind: Secret
metadata:
  namespace: prod-sosmed
  name: p-secret-fb
type: Opaque
data:
  DB_USER: ZGV2b3BzY2lsc3k=
  DB_PASS: MTIzNDU2Nzg5MA==

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prod-sosmed
  name: p-fb-configmap-secret
data:
  config.php: |
    <?php
    $db_host = "database-cilsy.cfigdwymc6w9.ap-southeast-1.rds.amazonaws.com";
    $db_user = getenv("DB_USER");
    $db_pass = getenv("DB_PASS");
    $db_name = "dbsosmed";
    try {    
      //create PDO connection
      $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
    } catch(PDOException $e) {
      //show error
      die("Terjadi masalah: " . $e->getMessage());
    }
    ?>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod-sosmed
  name: pesbuk-deployment
  labels:
    app: pesbuk-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pesbuk-deployment
  template:
    metadata:
      labels:
        app: pesbuk-deployment
    spec:
      volumes:
        - name: config-secret
          configMap:
            name: p-fb-configmap-secret
      containers:
      - name: pesbuk-deployment
        image: fiardika/pesbuk-jenkins:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-secret
          mountPath: "/var/www/html/config.php"
          subPath: "config.php"
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: p-secret-fb
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: p-secret-fb
              key: DB_PASS

---

kind: Service
apiVersion: v1
metadata:
  namespace: prod-sosmed
  name: pesbuk-service
spec:
  selector:
    app: pesbuk-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: prod-sosmed
  name: ingress
spec:
  rules:
  - host: pesbuk.fiardika.xyz
    http:
      paths:
        - backend:
           serviceName: pesbuk-service
           servicePort: 80
