
apiVersion: v1
kind: Secret
metadata:
  name: p-secret-fb
  namespace: production
type: Opaque
data:
  DB_USER: ZGV2b3BzY2lsc3kK
  DB_PASS: MTIzNDU2Nzg5MAo=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: p-fb-configmap-secret
  namespace: production
data:
  config.php: |
    <?php
    $db_host = "bigprodb.cfigdwymc6w9.ap-southeast-1.rds.amazonaws.com";
    $db_user = "devopscilsy";
    $db_pass = "1234567890";
    $db_name = "dbsosmed";
    try {    
      //create PDO connection
      $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
    } catch(PDOException $e) {
      //show error
      die("Terjadi masalah: " . $e->getMessage());
    }
    ?>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk-deployment
  namespace: production
  labels:
    app: pesbuk-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pesbuk-deployment
  template:
    metadata:
      labels:
        app: pesbuk-deployment
    spec:
      volumes:
        - name: config-secret
          configMap:
            name: p-fb-configmap-secret
      containers:
      - name: pesbuk-deployment
        image: fiardika/pesbuk-jenkins:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-secret
          mountPath: "/var/www/html/config.php"
          subPath: "config.php"
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: p-secret-fb
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: p-secret-fb
              key: DB_PASS

---

kind: Service
apiVersion: v1
metadata:
  name: pesbuk-service
  namespace: production
spec:
  selector:
    app: pesbuk-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: production
  annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.ingress.kubernetes.io/affinity: "cookie"
     nginx.ingress.kubernetes.io/session-cookie-name: "compro-prod-cookie"
     nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
     nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/affinity-mode: persistent
     nginx.ingress.kubernetes.io/session-cookie-hash: sha1
spec:
  rules:
  - host: pesbuk.fiardika.xyz
    http:
      paths:
        - backend:
           serviceName: pesbuk-service
           servicePort: 80
