apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: production
spec:
  rules:
  - host: pesbuk.fiardika.xyz
    http:
      paths:
        - backend:
            serviceName: pesbuk-service
            servicePort: 80
  - host: fiardika.fiardika.xyz
    http:
      paths:
        - backend:
            serviceName: landing-page-service
            servicePort: 80
  - host: blog.fiardika.xyz
    http:
      paths:
        - backend:
            serviceName: wordpress-service
            servicePort: 80
